# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
destination : "docs"
title: NFCities
email: info@nfciti.es
description: >- # this means to ignore newlines until "baseurl:"
  Randomly colored NFCities, prereleases are capped at 100 cities.

  Extra editions will be minted afterwards, but no more pre's, those are 1 of a kind.

  More info about the project will soon become public.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://homestead.box:4000/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  nfcities

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fa-envelope"
      url: "mailto:info@nfciti.es"
    - label: "Twitter"
      icon: "fa-twitter"
      # url: ""
    - label: "Opensea"
      icon: "fa-facebook-f"
      # url:
    - label: "GitHub"
      icon: "brands fa-github"
      url: "https://github.com/NFCities"
    - label: "GitLab"
      icon: "fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fa-instagram"
      # url:
  description: >- # this means to ignore newlines until "baseurl:"
    Randomly colored NFCities, prereleases are capped at 100 cities.
    <br />
    Extra editions will be minted afterwards, but no more pre's, those are 1 of a kind.
    <br />
    More info about the project will soon become public.
